[package]
name = "rustic_net"
version = "0.1.0"
edition = "2021"
authors = ["mtb0x1 <mtb0x10x1@gmail.com>"]
license-file = "LICENSE"

[features]
default = []
parallel = ["dep:rayon", "dep:lazy_static"]

[dependencies]
criterion = { version = "0.7.0", features = ["html_reports"]}
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
rand = "0.9.2"
approx = "0.5.1"
# Parallel processing
rayon = { version = "1.8", optional = true }
lazy_static = { version = "1.5.0", optional = true }

[[bench]]
name = "tensor_benchmarks"
harness = false
