name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
        components: rustfmt, clippy
    
    - name: Cache cargo registry
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
    
    - name: Build (release)
      run: cargo build --release --verbose

    - name: Build (release+parallel)
      run: cargo build --release --features parallel --verbose
    
    - name: Run tests (release)
      run: cargo test --release --verbose

    - name: Run tests (release+parallel)
      run: cargo test --release --features parallel --verbose
    
    - name: Check formatting
      run: cargo fmt -- --check
    
    - name: Run Clippy
      run: cargo clippy -- -D warnings

    - name: Run Clippy (release+parallel)
      run: cargo clippy --features parallel -- -D warnings 
