name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

jobs:
  test:
    name: Test ${{ matrix.features.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features:
          - name: no-features
            value: --no-default-features
          - name: simd
            value: --features simd
          - name: parallel
            value: --features parallel
          - name: simd_and_parallel
            value: --features simd_and_parallel

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        profile: minimal
        override: true
        components: clippy

    - name: Cache cargo registry
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ matrix.features.name }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-${{ matrix.features.name }}-
          ${{ runner.os }}-cargo-

    - name: Build
      run: cargo build --verbose --release ${{ matrix.features.value }}

    - name: Run tests
      run: cargo test --verbose --release ${{ matrix.features.value }}

    # disabled for now
    # - name: Run Clippy
    #   run: cargo clippy --release ${{ matrix.features.value }} -- -D warnings

  fmt-and-doc:
    name: Fmt and Doc
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        profile: minimal
        override: true
        components: rustfmt

    # disabled for now
    # - name: Check formatting
    #   run: cargo fmt -- --check

    - name: Generate docs
      run: |
        cargo doc --features docsrs --no-deps --document-private-items
        echo '<!DOCTYPE html>
        <html>
        <head>
            <meta http-equiv="refresh" content="0; url=./rustic_net/index.html" />
        </head>
        <body>
            <p>Redirecting to <a href="./rustic_net/index.html">documentation</a>...</p>
        </body>
        </html>' > target/doc/index.html

    - name: Upload documentation
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: target/doc/
        retention-days: 1

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: fmt-and-doc
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download documentation artifact
        uses: actions/download-artifact@v4
        with:
          name: documentation
          path: ./public
          
      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          static_site_generated: true
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'public'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4